# Generated by Django 4.2.25 on 2025-10-29 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_parent_user',
            field=models.BooleanField(default=False, help_text='Chỉ định xem user này có thể quản lý các user con hay không.', verbose_name='is parent user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_parent_user': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_users', to=settings.AUTH_USER_MODEL, verbose_name='Parent User'),
        ),
    ]
