# Generated by Django 4.2.25 on 2025-10-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_parent_user_alter_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/', verbose_name='ID Card Image'),
        ),
    ]
