# Generated by Django 4.2.25 on 2025-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_id_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_ids/', verbose_name='Face ID Image'),
        ),
    ]
