# Generated by Django 4.2.25 on 2025-10-31 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_cartitem'),
        ('users', '0005_user_address_user_face_id_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('assigned', 'Đã giao'), ('completed', 'Đã hoàn thành')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú (Staff)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày yêu cầu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('assigned_staff', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consults', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên tư vấn')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Dịch vụ quan tâm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_requests', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Yêu cầu Tư vấn',
                'verbose_name_plural': 'Các yêu cầu Tư vấn',
                'ordering': ['-created_at'],
            },
        ),
    ]
