# Generated by Django 4.2.25 on 2025-10-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Trường này chỉ Admin thấy', max_length=255, verbose_name='Supplier Name'),
        ),
    ]
