# Generated by Django 4.2.25 on 2025-10-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_thumbnail_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_price_on_contact',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu giá cần liên hệ.', verbose_name='Is Price on Contact'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
