# Generated by Django 4.2.25 on 2025-10-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_is_price_on_contact_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_days',
        ),
    ]
