# Generated by Django 4.2.25 on 2025-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_category_alter_service_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#333333', help_text='Nhập mã màu Hex, ví dụ: #e4002b', max_length=7, verbose_name='Color Code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_price_on_contact',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu giá cần liên hệ.', verbose_name='Is Price on Contact'),
        ),
    ]
