# Generated by Django 4.2.25 on 2025-11-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_supplier_color_supplier_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='color',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='logo',
        ),
    ]
