# Generated by Django 4.2.25 on 2025-11-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_supplier_color_remove_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='color',
            field=models.CharField(default='#333333', help_text='Nhập mã màu Hex (ví dụ: #333333)', max_length=7, verbose_name='Color Code'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_logos/', verbose_name='Logo'),
        ),
    ]
