# Generated by Django 4.2.25 on 2025-11-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_supplier_color_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Đã được admin xác nhận thanh toán/kích hoạt', verbose_name='Admin Verified'),
        ),
    ]
