# Generated by Django 4.2.25 on 2025-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_usersubscription_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Số ngày của gói dịch vụ', null=True, verbose_name='Duration (days)'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start Date'),
        ),
    ]
