# Generated by Django 4.2.25 on 2025-11-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Tự động tạo nếu để trống.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
